---
name: "Release"

on:
 push:
  branches:
   - "master"

jobs:
 GitHub:
  name: "Release - GitHub"
  runs-on: "ubuntu-latest"

  steps:
   - uses: actions/checkout@v2
   - name: "Install dependencies"
     run: |
      npm install

   - name: "Build"
     run: |
      npm run build

   - name: Draft release on GitHub
     uses: "marvinpinto/action-automatic-releases@latest"
     with:
      repo_token: "${{ secrets.GITHUB_TOKEN }}"
      automatic_release_tag: "latest"
      prerelease: true
      title: "Latest Release"
      files: |
       build/*
